'use client';

import { useState, useRef, useEffect, useCallback, useMemo } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'motion/react';
import { toast } from 'sonner';
import {
  Sparkles,
  X,
  Loader2,
  Copy,
  LayoutTemplate,
  ChevronDown,
  Check,
  Smartphone,
  Monitor,
  Clock,
  Zap,
  SlidersHorizontal,
  Wand2,
} from 'lucide-react';
import { useAIEmail } from '../hooks/useAIEmail';
import { getPreviewHtml, extractTemplateVars } from '@/src/lib/utils/templateParser';

interface AIComposePopoverProps {
  open: boolean;
  onClose: () => void;
  onInsert: (html: string, subject?: string) => void;
  onReplace: (html: string, subject?: string) => void;
  onApplyTemplate?: (
    html: string,
    templateName?: string,
    variables?: Record<string, string>,
    subject?: string
  ) => void;
  onUpdateSubject?: (subject: string) => void;
  recipientName?: string;
  subject?: string;
}
const TONES = ['Professional', 'Friendly', 'Formal', 'Urgent'] as const;

export function AIComposePopover({
  open,
  onClose,
  onInsert,
  onReplace,
  onApplyTemplate,
  onUpdateSubject,
  recipientName,
  subject,
}: AIComposePopoverProps) {
  const [mounted, setMounted] = useState(false);
  const [prompt, setPrompt] = useState('');
  const [editableSubject, setEditableSubject] = useState(subject || '');
  const [subjectAutoGenerated, setSubjectAutoGenerated] = useState(false);
  const [suggestingSubject, setSuggestingSubject] = useState(false);
  const [tone, setTone] = useState<string>('Professional');
  const [showToneDropdown, setShowToneDropdown] = useState(false);
  const [preview, setPreview] = useState('');
  const [previewDevice, setPreviewDevice] = useState<'desktop' | 'mobile'>('desktop');
  const [customVars, setCustomVars] = useState<Record<string, string>>({});
  const [showVarEditor, setShowVarEditor] = useState(true);
  const [templateMeta, setTemplateMeta] = useState<{
    templateName?: string;
    variables?: Record<string, string>;
  } | null>(null);
  const [copied, setCopied] = useState(false);
  const [elapsedTime, setElapsedTime] = useState(0);
  const [lastGenTime, setLastGenTime] = useState<number | null>(null);
  const timerRef = useRef<NodeJS.Timeout | null>(null);
  const { autoCompose, suggestSubject, loading, cancel } = useAIEmail();
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setMounted(true);
  }, []);

  // Keep editable subject synced when modal opens or subject prop changes
  useEffect(() => {
    if (open) {
      setEditableSubject(subject || '');
      setSubjectAutoGenerated(false);
    }
  }, [open, subject]);
  // Live stopwatch timer during generation
  useEffect(() => {
    if (loading) {
      setElapsedTime(0);
      const start = performance.now();
      timerRef.current = setInterval(() => {
        setElapsedTime(+((performance.now() - start) / 1000).toFixed(1));
      }, 100);
    } else {
      if (timerRef.current) {
        clearInterval(timerRef.current);
        timerRef.current = null;
      }
    }
    return () => {
      if (timerRef.current) {
        clearInterval(timerRef.current);
      }
    };
  }, [loading]);

  // Auto-focus input on open
  useEffect(() => {
    if (open) {
      const timer = setTimeout(() => inputRef.current?.focus(), 150);
      return () => clearTimeout(timer);
    }
  }, [open]);

  // Handle escape key
  useEffect(() => {
    if (!open) return;
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        handleClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [open]);

  // Close dropdown on outside click
  useEffect(() => {
    const handleClick = (e: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
        setShowToneDropdown(false);
      }
    };
    document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
  }, []);

  // Extracted variables from the generated template HTML
  const extractedVariables = useMemo(() => {
    if (!preview) return [];
    return extractTemplateVars(preview);
  }, [preview]);

  // Smart Auto-Fill helper
  // Comprehensive Smart Auto-Fill helper
  const runSmartAutoFill = useCallback(
    (htmlContent: string, currentPrompt: string, baseVars: Record<string, string> = {}) => {
      const vars = extractTemplateVars(htmlContent);
      const updated: Record<string, string> = { ...baseVars };
      const p = (currentPrompt || prompt).toLowerCase();

      vars.forEach((v) => {
        if (baseVars[v]) {
          updated[v] = baseVars[v];
          return;
        }
        const vLower = v.toLowerCase().replace(/_/g, '');

        if (
          vLower === 'name' ||
          vLower.includes('recipient') ||
          vLower.includes('customer') ||
          vLower.includes('candidate')
        ) {
          updated[v] = recipientName || 'Sanu Mishra';
        } else if (
          vLower.includes('leavestart') ||
          vLower.includes('startdate') ||
          vLower.includes('fromdate') ||
          vLower === 'start'
        ) {
          const dateObj = new Date();
          dateObj.setDate(dateObj.getDate() + 3);
          updated[v] = dateObj.toLocaleDateString('en-IN', {
            day: 'numeric',
            month: 'short',
            year: 'numeric',
          });
        } else if (
          vLower.includes('leaveend') ||
          vLower.includes('enddate') ||
          vLower.includes('todate') ||
          vLower === 'end'
        ) {
          const dateObj = new Date();
          dateObj.setDate(dateObj.getDate() + 7);
          updated[v] = dateObj.toLocaleDateString('en-IN', {
            day: 'numeric',
            month: 'short',
            year: 'numeric',
          });
        } else if (
          vLower.includes('totalday') ||
          vLower.includes('workingday') ||
          vLower.includes('duration') ||
          vLower.includes('days')
        ) {
          const match = p.match(/(\d+)\s*(?:day|days|working\s*day)/i);
          updated[v] = match ? match[1] : '4';
        } else if (
          vLower.includes('reason') ||
          vLower.includes('purpose') ||
          vLower.includes('cause')
        ) {
          if (
            p.includes('sick') ||
            p.includes('health') ||
            p.includes('medical') ||
            p.includes('doctor')
          ) {
            updated[v] = 'Medical recovery & health consultation';
          } else if (p.includes('vacation') || p.includes('trip') || p.includes('travel')) {
            updated[v] = 'Annual family travel & vacation';
          } else if (p.includes('emergency')) {
            updated[v] = 'Urgent family emergency';
          } else {
            updated[v] = 'Personal & family commitments';
          }
        } else if (
          vLower.includes('manager') ||
          vLower.includes('supervisor') ||
          vLower.includes('approver')
        ) {
          updated[v] = 'HR & Operations Management';
        } else if (
          vLower.includes('employee') ||
          vLower.includes('applicant') ||
          vLower.includes('sender')
        ) {
          updated[v] = recipientName || 'Sanu Mishra';
        } else if (
          vLower.includes('property') ||
          vLower.includes('project') ||
          vLower.includes('township') ||
          vLower.includes('plot')
        ) {
          if (p.includes('shivani') || p.includes('vatika')) {
            updated[v] = 'Plot #A-104, Shivani Vatika';
          } else if (p.includes('shyam') || p.includes('aangan')) {
            updated[v] = 'Unit #B-202, Shyam Aangan';
          } else if (p.includes('plot')) {
            const match = p.match(/plot\s*#?([a-z0-9-]+)/i);
            updated[v] = match ? `Plot #${match[1]}` : 'Plot #A-104, Shivani Vatika';
          } else {
            updated[v] = 'Shivani Vatika 11th';
          }
        } else if (
          vLower.includes('due') ||
          vLower.includes('amount') ||
          vLower.includes('emi') ||
          vLower.includes('price')
        ) {
          const match = p.match(/(?:rs\.?|inr|₹)?\s*(\d+[,\d]*k?|\d+000)/i);
          updated[v] = match ? (match[1].startsWith('₹') ? match[1] : `₹${match[1]}`) : '₹50,000';
        } else if (
          vLower.includes('missed') ||
          vLower.includes('count') ||
          vLower.includes('installments')
        ) {
          const match = p.match(/(\d+)\s*(?:month|emi|installment|missed)/i);
          updated[v] = match ? match[1] : '2';
        } else if (
          vLower.includes('role') ||
          vLower.includes('designation') ||
          vLower.includes('position')
        ) {
          if (p.includes('developer') || p.includes('react') || p.includes('fullstack')) {
            updated[v] = 'Full Stack Developer';
          } else if (p.includes('designer') || p.includes('ui') || p.includes('ux')) {
            updated[v] = 'UI/UX Design Specialist';
          } else if (p.includes('sales')) {
            updated[v] = 'Senior Sales Executive';
          } else {
            updated[v] = 'Freelance Consultant';
          }
        } else if (
          vLower.includes('compensation') ||
          vLower.includes('salary') ||
          vLower.includes('stipend') ||
          vLower.includes('fee')
        ) {
          const match = p.match(/(?:rs\.?|inr|₹)?\s*(\d+k|\d+,\d+|\d+000)/i);
          updated[v] = match
            ? match[1].startsWith('₹')
              ? `${match[1]} / month`
              : `₹${match[1]} / month`
            : '₹45,000 / month';
        } else if (vLower.includes('date') || vLower === 'date') {
          const dateObj = new Date();
          if (vLower.includes('due') || vLower.includes('start'))
            dateObj.setDate(dateObj.getDate() + 7);
          updated[v] = dateObj.toLocaleDateString('en-IN', {
            day: 'numeric',
            month: 'short',
            year: 'numeric',
          });
        } else if (vLower.includes('url') || vLower.includes('portal') || vLower.includes('link')) {
          updated[v] = 'https://www.sviinfrasolutions.com';
        } else if (!updated[v]) {
          const formatted = v
            .replace(/([a-z])([A-Z])/g, '$1 $2')
            .replace(/_/g, ' ')
            .replace(/\b\w/g, (c) => c.toUpperCase());
          updated[v] = formatted;
        }
      });

      return updated;
    },
    [prompt, recipientName]
  );

  const handleSmartAutoFill = useCallback(() => {
    if (!preview) return;
    const updated = runSmartAutoFill(preview, prompt, customVars);
    setCustomVars(updated);
  }, [preview, prompt, customVars, runSmartAutoFill]);
  const handleGenerate = useCallback(async () => {
    if (!prompt.trim() || loading) return;
    setPreview('');
    setTemplateMeta(null);
    setCustomVars({});
    setLastGenTime(null);
    const startTime = performance.now();

    try {
      const result = await autoCompose({
        prompt: prompt.trim(),
        subject: editableSubject.trim() || undefined,
        to: recipientName || undefined,
        tone,
        onChunk: (html) => {
          setPreview(html);
        },
      });

      const totalDuration = +((performance.now() - startTime) / 1000).toFixed(1);
      setLastGenTime(totalDuration);

      if (result && result.html) {
        setPreview(result.html);
        if (result.subject && result.subject.trim()) {
          setEditableSubject(result.subject.trim());
          setSubjectAutoGenerated(true);
        }
        setTemplateMeta({
          templateName: result.templateName,
          variables: result.variables,
        });

        // Automatically run smart variable extraction and auto-fill
        const populatedVars = runSmartAutoFill(result.html, prompt.trim(), result.variables || {});
        setCustomVars(populatedVars);
      }
    } catch (err) {
      console.error('[AICompose] Error generating:', err);
    }
  }, [prompt, editableSubject, tone, recipientName, autoCompose, loading, runSmartAutoFill]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleGenerate();
    }
  };

  // Build resolved preview HTML for iframe with luxury styling and high-contrast normalization
  const resolvedPreviewHtml = useMemo(() => {
    if (!preview) return '';
    const vars = extractTemplateVars(preview);
    const resolvedVars: Record<string, string> = {};

    vars.forEach((v) => {
      if (customVars[v] !== undefined && customVars[v].trim() !== '') {
        resolvedVars[v] = customVars[v];
      } else if (templateMeta?.variables?.[v]) {
        resolvedVars[v] = templateMeta.variables[v];
      } else if (v === 'name') {
        resolvedVars[v] = recipientName || 'Sanu Mishra';
      } else {
        resolvedVars[v] = `[${v.replace(/_/g, ' ').toUpperCase()}]`;
      }
    });

    const parsed = getPreviewHtml(preview, resolvedVars);

    const normalizerCss = `
      <style>
        * { box-sizing: border-box; }
        html, body {
          margin: 0 !important;
          padding: 0 !important;
          width: 100% !important;
          background-color: #f1f5f9 !important;
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif !important;
          color: #0f172a !important;
          -webkit-text-size-adjust: 100%;
          -ms-text-size-adjust: 100%;
          -webkit-font-smoothing: antialiased;
        }
        body {
          padding: 12px 6px !important;
        }
        table {
          border-collapse: collapse !important;
          mso-table-lspace: 0pt;
          mso-table-rspace: 0pt;
          max-width: 100% !important;
        }
        table[align="center"], table[style*="max-width:600px"], table[width="600"] {
          width: 100% !important;
          max-width: 600px !important;
          margin: 0 auto !important;
        }
        img { max-width: 100% !important; height: auto !important; }

        /* Guaranteed crisp high-contrast header text on dark navy banner */
        tr[style*="#0f172a"] h1, tr[style*="#0f172a"] p, tr[style*="#1e293b"] h1, tr[style*="#1e293b"] p,
        td[style*="#0f172a"] h1, td[style*="#0f172a"] p, td[style*="#1e293b"] h1, td[style*="#1e293b"] p,
        div[style*="#0f172a"] h1, div[style*="#0f172a"] p, div[style*="#1e293b"] h1, div[style*="#1e293b"] p {
          color: #ffffff !important;
        }
        tr[style*="#0f172a"] p, tr[style*="#1e293b"] p, td[style*="#0f172a"] p, td[style*="#1e293b"] p {
          color: #cbd5e1 !important;
        }
        tr[style*="#0f172a"] span, tr[style*="#1e293b"] span, td[style*="#0f172a"] span, td[style*="#1e293b"] span {
          color: #D4AF37 !important;
        }

        /* Table cards & structure styling */
        table td { word-break: break-word; }
        table[style*="border"] td, table[style*="background-color:#f8fafc"] td {
          padding: 10px 12px !important;
        }

        /* Guaranteed crisp high-contrast footer text & link styling */
        div[style*="text-align:center"] p {
          color: #334155 !important;
        }
        div[style*="text-align:center"] p:first-child {
          color: #0f172a !important;
          font-weight: 800 !important;
          font-size: 13px !important;
        }
        div[style*="text-align:center"] p:last-child {
          color: #64748b !important;
          font-weight: 600 !important;
        }
        div[style*="text-align:center"] a {
          color: #1e3a8a !important;
          font-weight: 700 !important;
          text-decoration: underline !important;
        }

        /* Mobile Responsive Viewport Overrides */
        @media only screen and (max-width: 600px) {
          body { padding: 8px 4px !important; }
          table[style*="max-width:600px"], table[width="600"] {
            width: 100% !important;
            border-radius: 10px !important;
          }
          td[style*="padding:36px"], td[style*="padding:32px"], td[style*="padding:40px"] {
            padding: 20px 14px !important;
          }
          h1[style*="font-size:24px"], h1[style*="font-size:28px"], h1[style*="font-size:22px"] {
            font-size: 19px !important;
            line-height: 1.3 !important;
          }
          h2[style*="font-size:18px"], h2[style*="font-size:19px"] {
            font-size: 16px !important;
          }
          table[style*="border-collapse"] td {
            padding: 8px 8px !important;
            font-size: 11.5px !important;
          }
          a[style*="padding:14px 36px"], a[style*="padding:14px 32px"] {
            display: block !important;
            width: 100% !important;
            box-sizing: border-box !important;
            text-align: center !important;
            padding: 13px 16px !important;
          }
        }
      </style>
    `;

    if (parsed.includes('<head>')) {
      return parsed.replace('<head>', `<head>${normalizerCss}`);
    } else if (parsed.includes('<html')) {
      return parsed.replace(/<html[^>]*>/, `$&<head>${normalizerCss}</head>`);
    } else {
      return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  ${normalizerCss}
</head>
<body>
  ${parsed}
</body>
</html>`;
    }
  }, [preview, customVars, templateMeta, recipientName]);
  const handleCopy = () => {
    if (!preview) return;
    const resolved = getPreviewHtml(preview, customVars);
    navigator.clipboard.writeText(resolved);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleQuickSuggestSubject = async () => {
    if (suggestingSubject) return;
    const textContext = preview || prompt;
    if (!textContext.trim()) {
      toast.info('Please write a prompt or generate email first');
      return;
    }
    setSuggestingSubject(true);
    try {
      const suggestions = await suggestSubject(textContext);
      if (suggestions && suggestions.length > 0) {
        setEditableSubject(suggestions[0]);
        setSubjectAutoGenerated(true);
        toast.success(`Generated Subject: ${suggestions[0]}`);
      }
    } catch (err) {
      console.error('Failed to suggest subject:', err);
    } finally {
      setSuggestingSubject(false);
    }
  };

  const handleApply = () => {
    if (!preview) return;
    if (editableSubject.trim()) {
      onUpdateSubject?.(editableSubject.trim());
    }
    if (onApplyTemplate) {
      onApplyTemplate(preview, templateMeta?.templateName, customVars, editableSubject.trim());
    } else {
      const resolved = getPreviewHtml(preview, customVars);
      onReplace(resolved, editableSubject.trim());
    }
    handleClose();
  };

  const handleInsert = () => {
    if (!preview) return;
    if (editableSubject.trim()) {
      onUpdateSubject?.(editableSubject.trim());
    }
    const resolved = getPreviewHtml(preview, customVars);
    onInsert(resolved, editableSubject.trim());
    handleClose();
  };

  const handleClose = () => {
    cancel();
    setPrompt('');
    setPreview('');
    setTemplateMeta(null);
    setCustomVars({});
    setLastGenTime(null);
    setElapsedTime(0);
    onClose();
  };
  if (!mounted) return null;

  return createPortal(
    <AnimatePresence>
      {open && (
        <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4 sm:p-6">
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/70 backdrop-blur-sm"
            onClick={handleClose}
          />

          {/* Modal Container */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 12 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 12 }}
            transition={{ type: 'spring', stiffness: 350, damping: 28 }}
            className="relative z-10 flex max-h-[92vh] w-full max-w-[700px] flex-col overflow-hidden rounded-2xl border border-gray-200/90 bg-white shadow-2xl dark:border-gray-700/70 dark:bg-[#121620]"
          >
            {/* Header */}
            <div className="flex items-center justify-between border-b border-gray-100 px-5 py-3.5 dark:border-gray-800">
              <div className="flex items-center gap-2.5">
                <div className="bg-brand-gold/15 text-brand-gold flex h-7 w-7 items-center justify-center rounded-lg">
                  <Sparkles className="h-4 w-4" />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h3 className="text-sm font-semibold text-gray-900 dark:text-white">
                      AI Email & Template Writer
                    </h3>
                    <span className="bg-brand-gold/15 text-brand-gold inline-flex items-center gap-1 rounded-full px-2.5 py-0.5 text-[10px] font-bold tracking-wide">
                      <Sparkles className="h-2.5 w-2.5" />
                      Enterprise AI
                    </span>
                  </div>
                  <p className="text-[11px] text-gray-500 dark:text-gray-400">
                    Generates official SVI Infra luxury corporate email templates
                  </p>
                </div>
              </div>
              <button
                onClick={handleClose}
                className="rounded-lg p-1.5 text-gray-400 transition-colors hover:bg-gray-100 hover:text-gray-600 dark:hover:bg-white/10 dark:hover:text-gray-200"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            {/* Content Body */}
            <div className="scrollbar-gold flex-1 space-y-4 overflow-y-auto p-5">
              {/* Subject Input Field (Auto Generated + Manually Editable) */}
              <div className="rounded-xl border border-gray-200/90 bg-gray-50/70 p-3.5 dark:border-gray-700/70 dark:bg-gray-900/60">
                <div className="mb-1.5 flex items-center justify-between">
                  <div className="flex items-center gap-1.5">
                    <label className="text-[11px] font-bold tracking-wider text-gray-700 uppercase dark:text-gray-300">
                      Email Subject
                    </label>
                    {subjectAutoGenerated ? (
                      <span className="inline-flex items-center gap-1 rounded-full bg-emerald-500/15 px-2 py-0.5 text-[9px] font-bold text-emerald-600 dark:text-emerald-400">
                        ✓ AI Generated
                      </span>
                    ) : (
                      <span className="text-[10px] text-gray-400 dark:text-gray-500">
                        (Auto-generates with draft or edit manually)
                      </span>
                    )}
                  </div>
                  <button
                    type="button"
                    onClick={handleQuickSuggestSubject}
                    disabled={suggestingSubject || (!prompt.trim() && !preview)}
                    className="text-brand-gold flex items-center gap-1 text-[11px] font-semibold transition-opacity hover:opacity-80 disabled:cursor-not-allowed disabled:opacity-40"
                    title="Generate or refresh subject suggestions with AI"
                  >
                    <Sparkles className="h-3 w-3" />
                    <span>{suggestingSubject ? 'Generating...' : '⚡ Auto-Suggest Subject'}</span>
                  </button>
                </div>
                <input
                  type="text"
                  value={editableSubject}
                  onChange={(e) => {
                    setEditableSubject(e.target.value);
                    setSubjectAutoGenerated(false);
                  }}
                  placeholder="Subject will auto-generate or type your own subject here..."
                  className="focus-gold w-full rounded-lg border border-gray-200 bg-white px-3 py-2 text-xs font-medium text-gray-900 placeholder-gray-400 transition-all outline-none dark:border-gray-700 dark:bg-gray-800 dark:text-white dark:placeholder-gray-500"
                />
              </div>

              {/* Prompt Input */}
              <div>
                <label className="mb-1.5 block text-xs font-medium text-gray-700 dark:text-gray-300">
                  What would you like to write?
                </label>
                <textarea
                  ref={inputRef}
                  value={prompt}
                  onKeyDown={handleKeyDown}
                  placeholder="e.g. welcome as freelance consultant for Shivani Vatika project at ₹50,000/month starting 1st September..."
                  rows={3}
                  className="focus-gold w-full resize-none rounded-xl border border-gray-200 bg-gray-50/80 p-3 text-sm text-gray-900 placeholder-gray-400 transition-all outline-none dark:border-gray-700 dark:bg-gray-900/70 dark:text-white dark:placeholder-gray-500"
                  disabled={loading}
                />
              </div>

              {/* Tone & Generate Action */}
              <div className="space-y-2">
                <div className="flex items-center gap-2.5">
                  <div ref={dropdownRef} className="relative">
                    <button
                      type="button"
                      onClick={() => setShowToneDropdown(!showToneDropdown)}
                      className="dark:hover:bg-gray-750 flex items-center gap-2 rounded-xl border border-gray-200 bg-gray-50/80 px-3.5 py-2 text-xs font-medium text-gray-700 transition-all hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-200"
                    >
                      <span>
                        Tone: <strong className="text-gray-900 dark:text-white">{tone}</strong>
                      </span>
                      <ChevronDown className="h-3.5 w-3.5 text-gray-400" />
                    </button>
                    {showToneDropdown && (
                      <div className="absolute bottom-full left-0 z-30 mb-1.5 w-40 overflow-hidden rounded-xl border border-gray-200 bg-white p-1 shadow-xl dark:border-gray-700 dark:bg-gray-800">
                        {TONES.map((t) => (
                          <button
                            key={t}
                            type="button"
                            onClick={() => {
                              setTone(t);
                              setShowToneDropdown(false);
                            }}
                            className={`flex w-full items-center justify-between rounded-lg px-3 py-1.5 text-xs font-medium transition-colors ${
                              tone === t
                                ? 'bg-brand-gold/15 text-brand-gold'
                                : 'text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-white/5'
                            }`}
                          >
                            {t}
                            {tone === t && <Check className="text-brand-gold h-3.5 w-3.5" />}
                          </button>
                        ))}
                      </div>
                    )}
                  </div>

                  <button
                    type="button"
                    onClick={handleGenerate}
                    disabled={!prompt.trim() || loading}
                    className="bg-brand-gold text-brand-dark-surface flex flex-1 items-center justify-center gap-2 rounded-xl px-4 py-2 text-xs font-semibold shadow-sm transition-all hover:brightness-105 active:scale-[0.98] disabled:opacity-50"
                  >
                    {loading ? (
                      <>
                        <Loader2 className="h-3.5 w-3.5 animate-spin" />
                        <span>
                          Generating SVI Template... (<strong>{elapsedTime.toFixed(1)}s</strong>)
                        </span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="h-3.5 w-3.5" />
                        <span>Generate Corporate Template</span>
                      </>
                    )}
                  </button>
                </div>

                {/* Live stopwatch while generating */}
                {loading && (
                  <motion.div
                    initial={{ opacity: 0, y: -4 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="flex items-center justify-between rounded-lg bg-amber-500/10 px-3 py-1.5 text-[11px] text-amber-700 dark:text-amber-300"
                  >
                    <div className="flex items-center gap-1.5">
                      <Clock className="h-3.5 w-3.5 animate-pulse text-amber-500" />
                      <span>
                        Elapsed time: <strong>{elapsedTime.toFixed(1)}s</strong> (Est. complete:
                        ~2-4s)
                      </span>
                    </div>
                    <span className="font-mono text-[10px] text-amber-600/80 dark:text-amber-400/80">
                      Generating structure...
                    </span>
                  </motion.div>
                )}
              </div>

              {/* Interactive Variable Fill Form (When template is generated) */}
              {preview && extractedVariables.length > 0 && (
                <motion.div
                  initial={{ opacity: 0, y: 6 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="border-brand-gold/30 bg-brand-gold/5 dark:border-brand-gold/20 dark:bg-brand-gold/[0.04] rounded-xl border p-4"
                >
                  <div className="mb-3 flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <div className="bg-brand-gold/20 text-brand-gold flex h-5 w-5 items-center justify-center rounded">
                        <SlidersHorizontal className="h-3 w-3" />
                      </div>
                      <span className="text-xs font-bold tracking-wider text-gray-900 uppercase dark:text-white">
                        Template Variables ({extractedVariables.length})
                      </span>
                      <span className="rounded bg-emerald-500/15 px-1.5 py-0.5 text-[9px] font-bold text-emerald-600 dark:text-emerald-400">
                        Live Sync
                      </span>
                    </div>

                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={handleSmartAutoFill}
                        className="bg-brand-gold/15 text-brand-gold hover:bg-brand-gold/25 flex items-center gap-1 rounded-lg px-2.5 py-1 text-[11px] font-semibold transition-colors"
                        title="Auto-fill details from your prompt"
                      >
                        <Wand2 className="h-3 w-3" />
                        <span>⚡ Re-Fill Fields</span>
                      </button>
                      <button
                        type="button"
                        onClick={() => setShowVarEditor(!showVarEditor)}
                        className="text-[11px] font-medium text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
                      >
                        {showVarEditor ? 'Collapse' : 'Expand'}
                      </button>
                    </div>
                  </div>

                  {showVarEditor && (
                    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                      {extractedVariables.map((v) => {
                        const val = customVars[v] || '';
                        const isFilled = Boolean(val.trim());
                        return (
                          <div key={v} className="flex flex-col">
                            <div className="mb-1 flex items-center justify-between">
                              <label className="text-[10px] font-bold tracking-wider text-gray-700 uppercase dark:text-gray-300">
                                {v.replace(/_/g, ' ')}
                              </label>
                              {isFilled ? (
                                <span className="text-[9px] font-semibold text-emerald-600 dark:text-emerald-400">
                                  ✓ Filled
                                </span>
                              ) : (
                                <span className="text-[9px] font-semibold text-amber-500">
                                  Required
                                </span>
                              )}
                            </div>
                            <input
                              type="text"
                              value={val}
                              onChange={(e) =>
                                setCustomVars((prev) => ({ ...prev, [v]: e.target.value }))
                              }
                              placeholder={`Enter ${v.replace(/_/g, ' ')}...`}
                              className="focus-gold w-full rounded-lg border border-gray-200 bg-white px-3 py-1.5 text-xs text-gray-900 placeholder-gray-400 transition-all outline-none dark:border-gray-700 dark:bg-gray-800 dark:text-white dark:placeholder-gray-500"
                            />
                          </div>
                        );
                      })}
                    </div>
                  )}
                </motion.div>
              )}
              {/* Output Preview (Sandboxed Iframe) */}
              {preview && (
                <div className="rounded-xl border border-gray-200/80 bg-gray-50/70 p-3.5 dark:border-gray-800 dark:bg-gray-900/60">
                  <div className="mb-2.5 flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <LayoutTemplate className="text-brand-gold h-3.5 w-3.5" />
                      <span className="text-xs font-semibold tracking-wider text-gray-700 uppercase dark:text-gray-300">
                        {templateMeta?.templateName || 'SVI Corporate Email Preview'}
                      </span>
                      {lastGenTime !== null && (
                        <span className="inline-flex items-center gap-1 rounded-md bg-emerald-500/15 px-2 py-0.5 text-[10px] font-bold text-emerald-600 dark:text-emerald-400">
                          ⚡ Took {lastGenTime}s
                        </span>
                      )}
                    </div>

                    <div className="flex items-center gap-3">
                      {/* Viewport device switcher */}
                      <div className="flex items-center rounded-lg border border-gray-200 bg-white p-0.5 dark:border-gray-700 dark:bg-gray-800">
                        <button
                          type="button"
                          onClick={() => setPreviewDevice('desktop')}
                          className={`rounded-md p-1 transition-colors ${
                            previewDevice === 'desktop'
                              ? 'bg-brand-gold/15 text-brand-gold'
                              : 'text-gray-400 hover:text-gray-600 dark:hover:text-gray-200'
                          }`}
                          title="Desktop view"
                        >
                          <Monitor className="h-3 w-3" />
                        </button>
                        <button
                          type="button"
                          onClick={() => setPreviewDevice('mobile')}
                          className={`rounded-md p-1 transition-colors ${
                            previewDevice === 'mobile'
                              ? 'bg-brand-gold/15 text-brand-gold'
                              : 'text-gray-400 hover:text-gray-600 dark:hover:text-gray-200'
                          }`}
                          title="Mobile view (375px)"
                        >
                          <Smartphone className="h-3 w-3" />
                        </button>
                      </div>

                      <button
                        type="button"
                        onClick={handleCopy}
                        className="hover:text-brand-gold flex items-center gap-1 text-[11px] font-medium text-gray-500 transition-colors dark:text-gray-400"
                        title="Copy HTML"
                      >
                        {copied ? (
                          <>
                            <Check className="h-3 w-3 text-emerald-500" />
                            <span className="text-emerald-500">Copied!</span>
                          </>
                        ) : (
                          <>
                            <Copy className="h-3 w-3" />
                            <span>Copy HTML</span>
                          </>
                        )}
                      </button>
                    </div>
                  </div>

                  {/* Sandboxed Iframe Container */}
                  <div className="flex justify-center overflow-hidden rounded-xl border border-gray-200 bg-[#f1f5f9] p-2 dark:border-gray-800">
                    <iframe
                      title="Corporate Email Preview"
                      srcDoc={resolvedPreviewHtml}
                      className={`h-[380px] rounded-lg border-0 bg-white shadow-md transition-all duration-200 ${
                        previewDevice === 'mobile' ? 'w-[375px]' : 'w-full'
                      }`}
                      sandbox="allow-same-origin"
                    />
                  </div>
                </div>
              )}
            </div>

            {/* Sticky Action Footer */}
            {preview && (
              <div className="flex items-center justify-between border-t border-gray-100 bg-gray-50/50 px-5 py-3 dark:border-gray-800 dark:bg-gray-900/40">
                <button
                  type="button"
                  onClick={handleClose}
                  className="rounded-lg px-3 py-1.5 text-xs font-medium text-gray-500 transition-colors hover:bg-gray-100 hover:text-gray-700 dark:text-gray-400 dark:hover:bg-white/5 dark:hover:text-gray-200"
                >
                  Discard
                </button>
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={handleInsert}
                    disabled={loading}
                    className="dark:hover:bg-gray-750 flex items-center gap-1.5 rounded-xl border border-gray-200/80 bg-white px-3 py-1.5 text-xs font-medium text-gray-700 transition-all hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-200"
                    title="Insert content into rich text editor"
                  >
                    <Copy className="h-3.5 w-3.5" />
                    <span>Insert Text</span>
                  </button>
                  <button
                    type="button"
                    onClick={handleApply}
                    disabled={loading}
                    className="bg-brand-gold text-brand-dark-surface flex items-center gap-1.5 rounded-xl px-4 py-1.5 text-xs font-semibold shadow-sm transition-all hover:brightness-105 active:scale-[0.98]"
                  >
                    <LayoutTemplate className="h-3.5 w-3.5" />
                    <span>Apply Corporate Template</span>
                  </button>
                </div>
              </div>
            )}
          </motion.div>
        </div>
      )}
    </AnimatePresence>,
    document.body
  );
}
